### ISSUE TITLE
jasmine.json helper path incorrect, or babel dependency wrong

### ISSUE THREAD

**Issue by ryanvanoss** [piecioshka/boilerplate-jasmine-babel#1]
Doing a clean `clone`, `npm install` and `npm test` fails with:

```
npm test

> test-jasmine-babel@ test /Users/rvanoss/repos/test-jasmine-babel
> jasmine JASMINE_CONFIG_PATH=test/jasmine.json

/Users/rvanoss/repos/test-jasmine-babel/test/spec/test.Foo.es6.js:1
(function (exports, require, module, __filename, __dirname) { import Foo from '../../app/scripts/core/Foo.es6';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/jasmine/lib/jasmine.js:63:5
    at Array.forEach (native)
    at Jasmine.loadSpecs (/usr/local/lib/node_modules/jasmine/lib/jasmine.js:62:18)
npm ERR! Test failed.  See above for more details.
```

The path in the `jasmine.json` points to `node_modules/babel-core`, but `package.json` uses `"babel": "^5.8.29"` as its `devDependency`.  I'm guessing that you either meant to point to `node_modules/babel` in `jasmine.json`, or declared `babel-core` as your `devDependency`.

**Comment by ryanvanoss** [comment]
FYI, I only checked by changing `babel-core` to `babel` and it runs fine. I didn't try pulling down `babel-core`, nor did I check using Babel 6.

**Comment by piecioshka** [comment]
Hi @ryanvanoss!
Thanks for testing!
Fixed by @8291ce0

Probably, you have older `npm` version.

**Comment by ryanvanoss** [comment]
Thanks for the fix! Yeah, I'm still sitting on `npm 2.14.7` from LTS node...

Completely aside, do you know what Jasmine integration will look like with Babel 6?

**Comment by piecioshka** [comment]
@ryanvanoss I am working on it ;)

Comming soon (in this repo).

**Comment by ryanvanoss** [comment]
:)

**Comment by ryanvanoss** [comment]
hey @piecioshka, did Babel 6 support ever land?

**Comment by piecioshka** [comment]
hey! Give me couple of days.

**Comment by piecioshka** [comment]
Hey @ryanvanoss !
This revision @5fcacd5be2548a5287a0a3048d794020391c4d82 support Babel 6.x
Thanks for your time, and sorry for my delay.

**Comment by jcity** [comment]
hey @piecioshka  - Looks like this one creeped up again

```
npm test

> test-jasmine-babel@ test /Users/jmyers/Downloads/test-jasmine-babel-master
> jasmine JASMINE_CONFIG_PATH=test/jasmine.json

/Users/jmyers/Downloads/test-jasmine-babel-master/test/specs/test.foo.es6.js:1
(function (exports, require, module, __filename, __dirname) { import Foo from '../../app/scripts/core/foo.es6';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/jasmine/lib/jasmine.js:71:5
    at Array.forEach (native)
npm ERR! Test failed.  See above for more details.
```
