### ISSUE TITLE
Path to babel core broken for jasmine 2.4

### ISSUE THREAD

**Issue by jcity** [piecioshka/boilerplate-jasmine-babel#2]
Doing a clean clone, npm install and npm test fails with

```
npm test

> convoy_offer_system@1.0.0 test /Users/jmyers/Justin/con/v0
> jasmine JASMINE_CONFIG_PATH=test/jasmine.json

/Users/jmyers/Justin/con/v0/test/specs/config.spec.js:1
(function (exports, require, module, __filename, __dirname) { import {Config} from '../../server/config/conf';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/jmyers/Justin/con/v0/node_modules/jasmine/lib/jasmine.js:71:5
    at Array.forEach (native)
npm ERR! Test failed.  See above for more details.
```

**Comment by jcity** [comment]
https://github.com/piecioshka/test-jasmine-babel/pull/3

Seems to fix the issue

**Comment by piecioshka** [comment]
@jcity thanks a lot!
